services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: my-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./back/.env

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: my-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
